"use strict";

import '../../css/bootstrap-flatly.css';
import './bootstrap';

import * as React from 'react';

export const About = React.createClass({
    render: function() {
      console.log("rendering About");
        return (
            <div>
<h2>About PseudoQ.net</h2>
  <p>The puzzles are currently randomly generated and selected.
     Also, the ratings may be a bit misleading.  Like, when it says &quot;Easy&quot;, it should probably be remembered
     that all things are relative.  
  </p>
  <p>An &quot;Easy&quot; rating implies that the puzzle is solvable using relatively simple strategies
     without any backtracking required. (Here &quot;Backtracking&quot; means to eliminate a possibility by first postulating it and 
     showing that it leads to a contradiction).  A &quot;Medium&quot; rating means that some backtracking is probably required. 
     A &quot;Hard&quot; rating means that it is beyond the capabilities of my current solver software to solve it with a moderately bounded
     level of backtracking.  
  </p>
  <p>Note that the player software itself is not intended to support backtracking - the user should perform the postulate/contradict
     process mentally, or externally to the software at least (pen and paper even?).  It is however possible to abuse the "Check" 
     functionality to allow guessing to be used, but this is definitely considered cheating, and will be severely frowned upon 
     by self-respecting, upright pseudo-citizens.
  </p>
  <p>
The main technologies used to create this site are 
    &nbsp;<a href='http://facebook.github.io/react'>React</a>, 
    &nbsp;<a href='http://getbootstrap.com'>Bootstrap</a>, 
    &nbsp;<a href='http://nodejs.org'>Node</a> and 
    &nbsp;<a href='http://koajs.com'>Koa</a>, with 
    &nbsp;<a href='http://webpack.github.io'>Webpack</a> and 
    &nbsp;<a href='http://gulpjs.com'>Gulp</a> used to streamline the build.  
The site is deployed on <a href='http://heroku.com'>Heroku</a>.
</p>
<p>The complete source code to this site, both client and server is now available on 
      &nbsp;<a href="https://github.com/stephensong/pseudoq">GitHub</a>.  
  I am hoping this might provide extra motivation for me to improve, refactor, clarify and document said code.

</p>
<p>
The puzzles themselves are generated by a codebase developed by myself from scratch in F#, currently running on .NET from my home.
</p>
<p>
The name &quot;PseudoQ&quot; was of my own invention.  Unfortunately, I very recently discovered there to have been a Java project with the same name 
released around 2005. This was disappointing to say the least.  My apologies if anybody out there takes offence at my hijacking of the name.  
It can, of course, be changed if needs be.
</p>
  <p>Current Version: 1.2.2
  </p>

<h2>About me</h2>
<p>
    My name is Gary Stephenson.
</p>
<p>
    I live in Sydney, Australia.  
    I have been a professional programmer for the last twenty years or so, and before that I programmed as a hobby/obsession since around 1980.  
    Here you can download my <a href='/resume.doc' download='resume.doc'>resume</a>.  Please <a href="mailto:stephensong2@gmail.com">contact me</a> if I might be of 
    assistance to you in any way.
</p>
  <p>This site has been created mainly to further develop my web programming skills. 
   (And I deny completely the vicious rumour that I do this only to indulge my killer-sudoku addiction, and pretend it&apos;s &quot;work&quot;.)
   Whilst it has taken far longer than I would ever have expected, with many a mis-step taken and dead-end explored along the way, 
   I do now consider myself to be at least reasonably competent as a Javascript developer, and am happy enough with the toolchain I currently work with.  
   Javascript development is fraught with choices.
</p>
<p>
    Fwiw, I am currently experimenting with (something like) a blog at <a href="https://www.pseudoq.net/#/blog">https://www.pseudoq.net/#/blog</a>. 
    Also, (something like) a link manager (a la Delicious) can be found at <a href="https://www.pseudoq.net/#/links">https://www.pseudoq.net/#/links</a>. 
    I remain uncertain as to whether I will make these a fully-fledged part of this site, or a separate site, or even ditch them altogether.
    Only time will tell.

</p>
<p>
    I&apos;m not currently on any social media to speak of, although I suspect I should be.  
</p>
            </div>
        );
    }
});

